"""initial migration

Revision ID: 48e1c3e7d0b2
Revises: None
Create Date: 2015-02-25 21:04:50.642516

"""

# revision identifiers, used by Alembic.
revision = '48e1c3e7d0b2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
